### ISSUE TITLE
Energy accounting functionalities for all zoom levels and timescales

### ISSUE THREAD

**Issue by GillisHommen** [Zenmo/zero_engine#1]
Energy accounting should include:
* Total energy use [kWh] (this is not the same as 'consumption' of energy carriers! Due to conversion assets)
* Total energy production [kWh] (this is not the same as 'production' of energy carriers! Due to conversion assets)
* Total energy import [kWh] (total and per energy carrier)
* Total energy export [kWh] (total and per energy carrier)
* Total energy curtailed [kWh] (electricity, optionally heat for residual heat sources with constant power)
* Consumption per energy carrier [kWh]
* Production per energy carrier [kWh]

* Change of energy content in buffers (heat stores, batteries, gas stores)

Zoom levels:
* Per gridconnection
* Per 'region' (depending on the project this may be a different thing; neighborhood, municipality, RES-regio, etc.)
* Per cooperative; not the same as per region.
* Model-wide (only this one is currently available in the model)

Timescales:
* Annual
* Weekly summer
* Weekly winter

Optional timescales:
* real-time? (in this case it will be _power_ accounting instead of _energy_ accounting)
* Last 24 hours?

Derived variables
If all of the previously mentioned totals are available, then for each timescale, scope and energy carrier it's possible to calculate:
* Self-consumed energy [kWh]
* Self-sufficiency [%]

**Comment by naudloomans** [comment]
@GillisHommen ik ga deze issue sluiten. Meeste is gedaan en specifieke nieuwe dingen als waterstof kunnen in kleinere issues worden uitgewerkt.
