### ISSUE TITLE
data_summerWeekNeighborhoodBatteryDemand_kW needs a more generic name is it is also used for household batteries

### ISSUE THREAD

**Issue by petertue** [Zenmo/zero_engine#36]

**Comment by petertue** [comment]
@GillisHommen ik maak hier even een issue van voor jou van omdat het geen functionaliteit is die ik wil toevoegen maar echt een engine convention keuze is. Heeft geen haast, puur even dat we het niet vergeten op termijn

**Comment by GillisHommen** [comment]
Will be part of next merge, however this is a breaking change for all interface models.

**Comment by GillisHommen** [comment]
data_summerWeekNeighborhoodBatteryDemand_kW  is nu data_summerWeekBatteryDemand_kW .
