### ISSUE TITLE
Belastingduurkromme komt niet overeen met netto load grafiek van een trafo

### ISSUE THREAD

**Issue by petertue** [Zenmo/zero_engine#65]
Leek me logisch te verklaren: doordat de accumulator met de lowPassedLoad value gevuld wordt ipv echte load. Maar ik heb nog steeds onderstaand 'probleem' als ik dat aanpas. Voordat ik een uur ga zitten debuggen, jullie weten vast waar dat vandaan komt.

Op dezelfde trafo pieken tot 600 kW in de netload grafiek, maar de belastingduurkromme van geeft piek van 250 kW. Er is duidelijk veel congestie, maar de belastingduurkromme laat dat niet zien.

![image](https://github.com/user-attachments/assets/aea1fd9e-121f-409d-b912-ec51a54b352c)

![image](https://github.com/user-attachments/assets/f1baa6f9-d6e2-47a0-ad2c-d0d45150bd39)

Bij nader inzien, hier lijkt iets anders mis te gaan. Kijkend naar de netto load zou zelfs de lowPassed waarde ver boven de 250 moeten komen gedurende meerdere tijdstappen achter elkaar...

**Comment by Luc-Sol** [comment]
Waarschijnlijk komt de low passed waarde hier wel boven de 250 uit voor enkele tijdstappen in het jaar, maar deze zijn slecht te zien in de belastingduurkromme. Je kunt in bepaalde versies van de resultsUI wel het maximale afgenomen vermogen zien en dat is dat vaak hoger dan wat er in het plaatje lijkt te staan.
